import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import FireFliesBackground from "./components/FireFliesBackground";
import BottonContact from "./components/BottonContact";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "DevMills",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* clsx se utliza para intercambiar nombres de clase */}
      <body className={clsx(inter.variable, "bg-background text-foreground font-inter")}>
      <div className="absolute'">
      {/* <BottonContact /> */}
      </div>
        {children}
        <FireFliesBackground></FireFliesBackground>
      </body>
    </html>
  );
}
